/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nus.web.rest;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author swemon
 */
@ApplicationPath("/api")
public class AppConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return super.getClasses(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(org.nus.web.rest.resource.AppointmentResource.class);
        resources.add(org.nus.web.rest.resource.PeopleResource.class);
    }
    
}
